config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "/tasks", to: "tasks#index"

  get "/tasks/new", to: "tasks#new", as: :new
  post "/tasks", to: "tasks#create"

  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "/tasks/:id", to: "tasks#update"

  get "/tasks/:id", to: "tasks#show", as: :task

  delete "tasks/:id", to: "tasks#destroy", as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @tasks = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.min.js" integrity="sha384-RuyvpeZCxMJCqVUGFI0Do1mQrods/hhxYlcVfGPOfQtPJh0JCw12tUAZ/Mv10S7D" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<br>
<%= form_with model: @task do |f| %>
  - <%= f.label :title %>
  <%= f.text_field :title, class: "input" %>
  - <%= f.label :details %>
  <%= f.text_field :details, class: "input" %>
  <%= f.submit :submit, class: "btn-form"%>
<% end %>
<hr>
<br>
<%= link_to "🔙 Back to tasks", task_path %>

app/views/tasks/index.html.erb
<h1>All your tasks</h1>
<ul>
  <% @tasks.each do |task| %>
  <li><%= link_to task.title, task_path(task) %></li>
  <% end %>
</ul>

<hr>
<br>
<%= link_to "➕ Add a new task", new_path %>

app/views/tasks/new.html.erb
<h1><u>Add a new Task</u></h1>
<br>
<%= form_with model: @task do |f| %>
  - <%= f.label :title %>
  <%= f.text_field :title, class: "input" %>
  - <%= f.label :details %>
  <%= f.text_field :details, class: "input" %>
  <%= f.submit :submit, class: "btn-form"%>
<% end %>
<hr>
<br>
<%= link_to "🔙 Back to tasks", tasks_path %>

app/views/tasks/show.html.erb
<div class="top">
  <h1>My tasks</h1>
  ✏️ <%= link_to "Edit task", edit_path %>
  ❌ <%= link_to "Delete", delete_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this task?"} %>
</div>


<div class="text">
  <label>- <%= @tasks.title %>
  <input type="checkbox">
  <span class="checkmark"></span>
</label>
</div>

<div class="details">
  <p><%= @tasks.details %></p>
</div>

<hr>
<br>
<div class="link-to">
  <%= link_to "📖 View all tasks", tasks_path %>
</div>